### ISSUE TITLE
[Default] AttributeError: type object 'tree_sitter.Language' has no attribute 'build_library'

### ISSUE THREAD

**Issue by impost0r** [interruptlabs/semgrep_bn#1]
Binary Ninja traceback:

```python3
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 127, in _default_action
[Default]     action(view_obj)
[Default]   File "/Users//user/Library/Application Support/Binary Ninja/plugins/semgrep_bn/__init__.py", line 462, in run
[Default]     SemgrepAnalysis(bv).start()
[Default]   File "/Users/user/Library/Application Support/Binary Ninja/plugins/semgrep_bn/__init__.py", line 254, in __init__
[Default]     Language.build_library(str(TREE_SITTER_LIB), [str(TREE_SITTER_C)])
[Default] AttributeError: type object 'tree_sitter.Language' has no attribute 'build_library'
```

Python 3.11 autocomplete suggests that build_library was removed from the .Language member.
```python3
Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tree_sitter
>>> tree_sitter.Language.
tree_sitter.Language.field_count
tree_sitter.Language.field_id_for_name(
tree_sitter.Language.field_name_for_id(
tree_sitter.Language.id_for_node_kind(
tree_sitter.Language.lookahead_iterator(
tree_sitter.Language.mro()
tree_sitter.Language.next_state(
tree_sitter.Language.node_kind_count
tree_sitter.Language.node_kind_for_id(
tree_sitter.Language.node_kind_is_named(
tree_sitter.Language.node_kind_is_visible(
tree_sitter.Language.parse_state_count
tree_sitter.Language.query(
tree_sitter.Language.version
```

**Comment by impost0r** [comment]
Also, the semgrep rule selection popup does not work.

**Comment by 0xricksanchez** [comment]
It seems like `tree-sitter` reworked their API and removed the `build_library` in one of their [more recent releases](https://github.com/tree-sitter/py-tree-sitter/releases/tag/v0.22.0).

**Comment by adrianherrera** [comment]
@impost0r sorry for the delay; I don't get updates for this repo so didn't see the issue.

Does @0xricksanchez' PR fix your problems?

**Comment by impost0r** [comment]
Let me check if it actually fixes it on my laptop. My laptop is a bit... special, so let's see.

**Comment by impost0r** [comment]
Should work, just needs updating in the Binary Ninja repos now.

**Comment by impost0r** [comment]
> Should work, just needs updating in the Binary Ninja repos now.

Scratch that, for some reason it doesn't show up in the plugins menu now. At least on macOS.

**Comment by adrianherrera** [comment]
Ah ok I think I need to make a new release given the version number in the
json changed.

Let me re-read up on binja plugin releases lol…

**Comment by adrianherrera** [comment]
Ok I've pushed out a new release. Hopefully that makes it reappear!
